name: Build and Test Generation
on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Cache maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Install autorest'
        run: |
          npm install -g autorest
      - name: Setup jdk 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Clone autorest.java
        run: git clone --depth 1 https://github.com/azure/autorest.java
      - name: Build and Package
        run: mvn -f autorest.java/pom.xml -Plocal package --no-transfer-progress

      - name: Clone azure-sdk-for-java
        run: git clone --depth 1 https://github.com/azure/azure-sdk-for-java
      - name: Install sdk-build-tools
        run: mvn -f azure-sdk-for-java/eng/code-quality-reports/pom.xml install --no-transfer-progress

      - name: Generate and Compile
        run: |
          rm -rf generated
          ./gen.py -u ./autorest.java -o azure-sdk-for-java
          ./update_pom.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git pull --rebase=false --no-edit
          git push
          {
            git add generated test && \
            git commit -m '[Automation] Generated Fluent Lite' && \
            git push
          } || true
