name: Build and Test Generation
on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci
          fetch-depth: 0
      - name: Merge from Azure/autorest.java
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git pull --rebase=false --no-edit https://github.com/azure/autorest.java main

      - name: Cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: 'Install autorest'
        run: |
          npm install -g autorest
          npm install --no-bin-links
      - name: Setup jdk 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Package
        run: mvn -f pom.xml -Dlocal package
      - name: clone azure-sdk-for-java
        run: git clone --depth 1 https://github.com/azure/azure-sdk-for-java
      - name: Install sdk-build-tools
        run: mvn -f azure-sdk-for-java/eng/code-quality-reports/pom.xml install
      - name: Generate and Compile
        run: |
          rm -rf generated
          ./gen.py -u . -o azure-sdk-for-java
          ./update_pom.py

      - name: Commit and push
        run: |
          git pull --rebase=false --no-edit https://github.com/chentanyi/autorest.java ci
          git push
          {
            git add generated test && \
            git commit -m '[Automation] Generated Fluent Lite' && \
            git push
          } || true